services:
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin
    ports:
      - 8096:8096
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/jellyfin:/config
      - ${DATA_PATH}/media:/data/media
    networks:
      - ${DOCKER_NETWORK}
  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    networks:
      - ${DOCKER_NETWORK}
    restart: unless-stopped
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    networks:
      - ${DOCKER_NETWORK}
    ports:
      - "9696:9696"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/prowlarr:/config
    restart: unless-stopped
    depends_on:
    - flaresolverr
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    networks:
      - ${DOCKER_NETWORK}
    ports:
      - "7878:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${DATA_PATH}:/data
    restart: unless-stopped
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    networks:
      - ${DOCKER_NETWORK}
    ports:
      - "8989:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${DATA_PATH}:/data
    restart: unless-stopped
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr
    networks:
      - ${DOCKER_NETWORK}
    ports:
      - "6767:6767"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/bazarr:/config
      - ${DATA_PATH}/media:/data/media
    restart: unless-stopped
    depends_on:
    - radarr
    - radarr-uhd
    - sonarr
    - sonarr-uhd
  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr
    networks:
      - ${DOCKER_NETWORK}
    ports:
      - "8686:8686"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/lidarr:/config
      - ${DATA_PATH}:/data
    restart: unless-stopped
  readarr:
    container_name: readarr
    image: ghcr.io/hotio/readarr
    networks:
      - ${DOCKER_NETWORK}
    ports:
      - "8787:8787"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/readarr:/config
      - ${DATA_PATH}:/data
    restart: unless-stopped
  jellyseerr:
    container_name: jellyseerr
    image: ghcr.io/hotio/jellyseerr
    networks:
      - ${DOCKER_NETWORK}
    ports:
      - "5055:5055"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/jellyseerr:/config
    restart: unless-stopped
    depends_on:
    - jellyfin
    - radarr
    - sonarr
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    networks:
      - ${DOCKER_NETWORK}
    ports:
      - "8080:8080"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - ${CONFIG_PATH}/qbittorrent:/config
      - ${DATA_PATH}/torrents:/data/torrents
    restart: unless-stopped
  unpackerr:
    container_name: unpackerr
    image: ghcr.io/hotio/unpackerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/unpacker:/config
      - ${DATA_PATH}:/data
    restart: unless-stopped