services:
  caddy:
    container_name: caddy
    image: ghcr.io/hotio/caddy
    ports:
      - 80:80
      - 443:443
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Madrid
      - CLOUDFLARE_API_TOKEN=p0c_Ko4m2zpfcSYwyqnUnCybJb3Xx3lHm0XimTpC
    volumes:
      - /opt/stacks/caddy:/config
    networks:
      - voynet
    restart: unless-stopped
networks:
  voynet:
    external: true