services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    networks:
      - ${DOCKER_NETWORK}
    ports:
      - 3001:3001
    volumes:
      - ${CONFIG_PATH}/uptime-kuma:/app/data
    restart: always