services:
  dockge:
    container_name: dockge
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_PATH}/dockge/data:/app/data
      - ${CONFIG_PATH}/dockge/stacks:${CONFIG_PATH}/dockge/stacks
    environment:
      - DOCKGE_STACKS_DIR=${CONFIG_PATH}/dockge/stacks
      